apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: console-audit-bff-custom-secrets
spec:
  backendType: secretsManager
  region: sa-east-1
  data:
    - key: /v1/console-audit-bff/global/app-secrets
      name: AWS_ACCESS_KEY_ID
      property: key_id
    - key: /v1/console-audit-bff/global/app-secrets
      name: AWS_SECRET_ACCESS_KEY
      property: secret
