// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package entity

type DisputeEvent struct {
	ID                      int     `json:"id"`
	OrdID                   int     `json:"ord_id"`
	AccountID               int     `json:"account_id"`
	AuthorizationID         int     `json:"authorization_id"`
	Comment                 string  `json:"comment"`
	DisputeReason           int     `json:"dispute_reason"`
	Modality                int     `json:"modality"`
	DisputeStatus           int     `json:"dispute_status"`
	DisputeStatusGroup      string  `json:"dispute_status_group"`
	CreatedAt               string  `json:"created_at"`
	UpdatedAt               *string `json:"updated_at,omitempty"`
	CreatedAtUtc            *string `json:"created_at_utc,omitempty"`
	UpdatedAtUtc            *string `json:"updated_at_utc,omitempty"`
	Timeline                *string `json:"timeline,omitempty"`
	Protocol                *string `json:"protocol,omitempty"`
	Metadata                *string `json:"metadata,omitempty"`
	DisputedAmount          float64 `json:"disputed_amount"`
	IsNetwork               bool    `json:"is_network"`
	IsDisputeMigrated       bool    `json:"is_dispute_migrated"`
	ReversalID              *int    `json:"reversal_id,omitempty"`
	NetworkReturnReasonCode *string `json:"network_return_reason_code,omitempty"`
	NetworkBrandType        string  `json:"network_brand_type"`
	TransactionDate         string  `json:"transaction_date"`
}

type DisputeEventInput struct {
	Event                       string  `json:"event"`
	Reason                      string  `json:"reason"`
	DisputeInstallmentID        *string `json:"dispute_installment_id,omitempty"`
	Memo                        *string `json:"memo,omitempty"`
	MerchantName                *string `json:"merchant_name,omitempty"`
	UpdatedChargebackReasonCode *string `json:"updated_chargeback_reason_code,omitempty"`
	ChangeReasonCodeReason      *string `json:"change_reason_code_reason,omitempty"`
	PreArbIsPartial             *bool   `json:"pre_arb_is_partial,omitempty"`
	PreArbCurrencyCode          *string `json:"pre_arb_currency_code,omitempty"`
	JustifyNotAcceptedFully     *string `json:"justify_not_accepted_fully,omitempty"`
	PreArbAmount                *int    `json:"pre_arb_amount,omitempty"`
	IsDisputeMigrated           *bool   `json:"is_dispute_migrated,omitempty"`
}

type DisputeStatus struct {
	Source string `json:"source"`
	Target string `json:"target"`
	Event  string `json:"event"`
}

type FraudReport struct {
	FraudReportID        int `json:"fraud_report_id"`
	DisputeID            int `json:"dispute_id"`
	DisputeInstallmentID int `json:"dispute_installment_id"`
}

type FraudReportInput struct {
	AcctStatus          string `json:"acct_status"`
	ChgbkIndicator      string `json:"chgbk_indicator"`
	CvcInvalidIndicator string `json:"cvc_invalid_indicator"`
	DeviceType          string `json:"device_type"`
	FraudType           string `json:"fraud_type"`
	ReportDate          string `json:"report_date"`
	SubType             string `json:"sub_type"`
}

type Health struct {
	Message string `json:"message"`
}

type Mutation struct {
}

type Query struct {
}

