apiVersion: v1
kind: ConfigMap
metadata:
  name: 'backoffice-core-bff-config'
  namespace: 'psm-crm'
data:
  ENVIRONMENT: 'irl-prod'
  CORS_ALLOWED_METHODS: "GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS"
  SNS_CONSOLE_AUDIT: "arn:aws:sns:eu-west-1:471112918407:console-audit"
