apiVersion: v1
kind: ConfigMap
metadata:
  name: backoffice-core-bff-config
  namespace: {{ index .Values "rollout-Canary" "namespace" }}
data:
  ENVIRONMENT: {{ index .Values "rollout-Canary" "environment" | quote }}
  LOCATION: "Etc/GMT+0"
  HTTP_DEFAULT_TIMEOUT: "60"
  SNS_CONSOLE_AUDIT: "arn:aws:sns:us-east-1:459584242408:console-audit"
  CORS_ALLOWED_METHODS: "GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS"
