# rollout template configs
rollout-Canary:
  squad: psm-console
  fullnameOverride: "console-audit-bff"
  domain: irl.pismo.io
  environment: irl-prod
  revisionHistoryLimit: 10
  ports:
    http: 8080
  metrics:
    enabled: true
    path: /metrics
  health:
    enabled: true
    path: /health
  replicas: 3
  hpa:
    enabled: true
    maxReplicas: 5
    minReplicas: 3
  image:
    registry: 270036487593.dkr.ecr.us-east-1.amazonaws.com
    repository: console-audit-bff
    imagePullPolicy: Always
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 1m
      memory: 16Mi
  strategy:
    canary:
      analysis: {}
  envFrom:
    - configMapRef:
        name: commons-config
    - configMapRef:
        name: console-audit-bff-config
    - secretRef:
        name: console-audit-bff-app-secrets
  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::471112918407:role/console-audit-bff-role-euw1
  pod:
    annotations: {}
  virtualService:
    extraGateways:
      - irl-prod/istio-gateway-internal
