apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: console-audit-bff-secrets
spec:
  backendType: secretsManager
  roleArn: 'arn:aws:iam::056132470094:role/console-audit-bff-role-aps2'
  region: ap-south-2
  data:
    - key: /v1/console-audit-bff/global/app-secrets
      name: KEY_ID
      property: key_id
    - key: /v1/console-audit-bff/global/app-secrets
      name: SECRET
      property: secret

