apiVersion: v1
kind: ConfigMap
metadata:
  name: 'console-audit-bff-config'
  namespace: 'psm-console'
data:
  ENVIRONMENT: 'aus-prod'
  CORS_ALLOWED_METHODS: "GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS"
