apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: 'console-audit-bff-app-secrets'
spec:
  backendType: secretsManager
  roleArn: 'arn:aws:iam::008594187592:role/console-audit-bff-role-use2'
  region: 'us-east-2'
  data:
    - key: /v1/console-audit-bff/global/app-secrets
      name: KEY_ID
      property: key_id
    - key: /v1/console-audit-bff/global/app-secrets
      name: SECRET
      property: secret
